# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AQIAssignment' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'CorePlot', '~> 2.3'
  # Pods for AQIAssignment

  target 'AQIAssignmentTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AQIAssignmentUITests' do
    # Pods for testing
  end

end
